[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "hedgehog dignity state sting dove remember genre empower certain business luggage crime jump issue crowd rib cupboard ranch medal spy canvas organ symbol proof"
